import pandas as pd
import os

products_path = "data/products.csv"
existing_df = pd.read_csv(products_path)

# New realistic accessible & clinical skincare products (Minimalist, CeraVe, Cetaphil, Cosrx, Derma Co, etc.)
new_products = [
    # Cleansers
    {
        "product_id": "IND_CLN_01",
        "name": "Oat Extract 06% Gentle Cleanser",
        "brand": "Minimalist",
        "category": "Cleanser",
        "price": 299.0,
        "ingredients": "['Oat Extract', 'Sodium Lauroyl Oat Amino Acids', 'Glycerin', 'Panthenol', 'Hyaluronic Acid', 'Phenoxyethanol']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['sensitive', 'dry', 'normal', 'combination']",
        "concerns": "['redness', 'barrier_repair', 'dryness']",
        "rating": 4.6,
        "description": "Minimalist Oat Extract 06% Gentle Soothing Cleanser for Sensitive & Barrier Compromised Skin",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_CLN_02",
        "name": "Salicylic Acid 02% Daily Face Cleanser",
        "brand": "Minimalist",
        "category": "Cleanser",
        "price": 299.0,
        "ingredients": "['Salicylic Acid', 'Capryloyl Salicylic Acid', 'Zinc PCA', 'Glycerin', 'Betaine', 'Sodium Lauroyl Sarcosinate']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['oily', 'combination']",
        "concerns": "['acne', 'oiliness', 'enlarged_pores']",
        "rating": 4.7,
        "description": "Minimalist Salicylic Acid 2% BHA gentle anti-acne sebum control cleanser",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_CLN_03",
        "name": "Gentle Skin Cleanser for Sensitive Skin",
        "brand": "Cetaphil",
        "category": "Cleanser",
        "price": 375.0,
        "ingredients": "['Water', 'Glycerin', 'Cetearyl Alcohol', 'Panthenol', 'Niacinamide', 'Sodium Cocoyl Isethionate']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['sensitive', 'dry', 'normal', 'combination']",
        "concerns": "['dryness', 'redness', 'barrier_repair']",
        "rating": 4.8,
        "description": "Cetaphil Hydrating Non-Foaming Gentle Skin Cleanser with Niacinamide & Panthenol",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_CLN_04",
        "name": "Hydrating Facial Cleanser for Normal to Dry Skin",
        "brand": "CeraVe",
        "category": "Cleanser",
        "price": 420.0,
        "ingredients": "['Aqua', 'Glycerin', 'Cetearyl Alcohol', 'Ceramide NP', 'Ceramide AP', 'Ceramide EOP', 'Phytosphingosine', 'Hyaluronic Acid']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['dry', 'normal', 'sensitive']",
        "concerns": "['dryness', 'barrier_repair']",
        "rating": 4.8,
        "description": "CeraVe Hydrating Cleanser with 3 Essential Ceramides & Hyaluronic Acid",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_CLN_05",
        "name": "Low pH Good Morning Gel Cleanser",
        "brand": "COSRX",
        "category": "Cleanser",
        "price": 490.0,
        "ingredients": "['Water', 'Cocamidopropyl Betaine', 'Sodium Lauroyl Methyl Isethionate', 'Tea Tree Leaf Oil', 'Betaine Salicylate', 'Allantoin']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['oily', 'combination', 'sensitive']",
        "concerns": "['acne', 'oiliness', 'enlarged_pores']",
        "rating": 4.6,
        "description": "COSRX Low pH Gentle Morning Gel Cleanser with Tea Tree and Betaine Salicylate BHA",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_CLN_06",
        "name": "1% Salicylic Acid Foaming Gel Cleanser",
        "brand": "The Derma Co",
        "category": "Cleanser",
        "price": 279.0,
        "ingredients": "['Salicylic Acid', 'Zinc PCA', 'Witch Hazel Extract', 'Glycerin', 'Sodium Lauroyl Sarcosinate']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['oily', 'combination']",
        "concerns": "['acne', 'oiliness', 'blackheads']",
        "rating": 4.4,
        "description": "The Derma Co 1% Salicylic Acid Daily Active Exfoliating Cleanser",
        "evidence_tags": "['clinically_tested']"
    },

    # Treatments & Serums
    {
        "product_id": "IND_TRT_01",
        "name": "Niacinamide 10% + Zinc 1% Face Serum",
        "brand": "Minimalist",
        "category": "Treatment",
        "price": 599.0,
        "ingredients": "['Niacinamide 10%', 'Zinc PCA 1%', 'EUK 134', 'Aloe Vera Juice', 'Glycerin', 'Hyaluronic Acid']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['oily', 'combination', 'normal']",
        "concerns": "['acne', 'hyperpigmentation', 'oiliness', 'enlarged_pores']",
        "rating": 4.7,
        "description": "Minimalist Niacinamide 10% + Zinc Serum for Blemish Reductions and Sebum Regulation",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_TRT_02",
        "name": "Salicylic Acid 02% Clarifying Face Serum",
        "brand": "Minimalist",
        "category": "Treatment",
        "price": 549.0,
        "ingredients": "['Salicylic Acid 2%', 'Oligopeptide-10', 'Aloe Vera Juice', 'Glycerin', 'Propylene Glycol']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['oily', 'combination']",
        "concerns": "['acne', 'blackheads', 'enlarged_pores', 'oiliness']",
        "rating": 4.6,
        "description": "Minimalist 2% Salicylic Acid BHA Serum for Active Acne and Blackheads",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_TRT_03",
        "name": "Alpha Arbutin 02% + Hyaluronic Acid Anti-Pigmentation Serum",
        "brand": "Minimalist",
        "category": "Treatment",
        "price": 549.0,
        "ingredients": "['Alpha Arbutin 2%', 'Hyaluronic Acid', 'Hydroxyphenoxy Propionic Acid', 'Glycerin', 'Aloe Vera']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['oily', 'combination', 'dry', 'normal', 'sensitive']",
        "concerns": "['hyperpigmentation', 'dullness', 'pigmentation']",
        "rating": 4.6,
        "description": "Minimalist Alpha Arbutin 2% Brightening and Dark Spot Removal Clinical Serum",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_TRT_04",
        "name": "Granactive Retinoid 02% Anti-Aging Night Emulsion",
        "brand": "Minimalist",
        "category": "Treatment",
        "price": 699.0,
        "ingredients": "['Hydroxypinacolone Retinoate 2%', 'Dimethyl Isosorbide', 'Squalane', 'Tocopherol', 'Bakuchiol']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['dry', 'combination', 'normal']",
        "concerns": "['anti_aging', 'wrinkles', 'fine lines', 'dullness']",
        "rating": 4.7,
        "description": "Minimalist Granactive Retinoid 2% Gentle Anti-Aging Emulsion with Bakuchiol",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_TRT_05",
        "name": "Centella Asiatica 10% Calming Serum",
        "brand": "Minimalist",
        "category": "Treatment",
        "price": 499.0,
        "ingredients": "['Centella Asiatica Extract', 'Madecassoside', 'Panthenol', 'Allantoin', 'Hyaluronic Acid', 'Glycerin']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['sensitive', 'dry', 'combination']",
        "concerns": "['redness', 'barrier_repair', 'inflammation']",
        "rating": 4.8,
        "description": "Minimalist Centella Soothing & Barrier Restoration Serum for Reactive Red Skin",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_TRT_06",
        "name": "Advanced Snail 96 Mucin Power Essence",
        "brand": "COSRX",
        "category": "Treatment",
        "price": 890.0,
        "ingredients": "['Snail Secretion Filtrate 96%', 'Betaine', 'Sodium Hyaluronate', 'Allantoin', 'Panthenol', 'Arginine']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['dry', 'combination', 'normal', 'sensitive']",
        "concerns": "['dryness', 'barrier_repair', 'dullness']",
        "rating": 4.9,
        "description": "COSRX Snail Mucin 96 Essence for Deep Cellular Hydration and Repair",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_TRT_07",
        "name": "10% Vitamin C + 5% Niacinamide Glowing Face Serum",
        "brand": "The Derma Co",
        "category": "Treatment",
        "price": 499.0,
        "ingredients": "['Ethyl Ascorbic Acid 10%', 'Niacinamide 5%', 'Hyaluronic Acid', 'Ferulic Acid', 'Glycerin']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['normal', 'combination', 'oily']",
        "concerns": "['dullness', 'hyperpigmentation', 'pigmentation']",
        "rating": 4.5,
        "description": "The Derma Co 10% Vitamin C Radiance & Collagen Boosting Serum",
        "evidence_tags": "['clinically_tested']"
    },

    # Moisturizers
    {
        "product_id": "IND_MST_01",
        "name": "Ceramides 0.3% + Madecassoside Moisturizer",
        "brand": "Minimalist",
        "category": "Moisturizer",
        "price": 599.0,
        "ingredients": "['Ceramide NP', 'Ceramide AP', 'Ceramide EOP', 'Madecassoside', 'Centella Asiatica', 'Glycerin', 'Squalane', 'Ursolic Acid']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['dry', 'sensitive', 'normal']",
        "concerns": "['barrier_repair', 'dryness', 'redness']",
        "rating": 4.8,
        "description": "Minimalist 0.3% Pure Ceramides Barrier Repairing Intensive Cream with Madecassoside",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_MST_02",
        "name": "Vitamin B5 10% Oil-Free Gel Moisturizer",
        "brand": "Minimalist",
        "category": "Moisturizer",
        "price": 349.0,
        "ingredients": "['Panthenol 10%', 'Zinc PCA', 'Magnesium Aspartate', 'Copper Gluconate', 'Betaine', 'Hyaluronic Acid']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['oily', 'combination']",
        "concerns": "['oiliness', 'acne', 'enlarged_pores']",
        "rating": 4.6,
        "description": "Minimalist Vitamin B5 Lightweight Oil-Free Gel Hydrator for Oily Acne-Prone Skin",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_MST_03",
        "name": "Daily Advance Ultra Hydrating Lotion",
        "brand": "Cetaphil",
        "category": "Moisturizer",
        "price": 460.0,
        "ingredients": "['Aqua', 'Glycerin', 'Hydrogenated Polyisobutene', 'Cetearyl Alcohol', 'Butyrospermum Parkii Butter', 'Macadamia Nut Oil', 'Panthenol', 'Tocopheryl Acetate']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['dry', 'sensitive', 'normal']",
        "concerns": "['dryness', 'barrier_repair', 'redness']",
        "rating": 4.7,
        "description": "Cetaphil Daily Advance 24h Clinically Proven Barrier Replenishing Lotion",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_MST_04",
        "name": "Daily Moisturizing Lotion with 3 Essential Ceramides",
        "brand": "CeraVe",
        "category": "Moisturizer",
        "price": 490.0,
        "ingredients": "['Aqua', 'Glycerin', 'Caprylic/Capric Triglyceride', 'Ceramide NP', 'Ceramide AP', 'Ceramide EOP', 'Hyaluronic Acid', 'Cholesterol']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['dry', 'combination', 'normal', 'sensitive']",
        "concerns": "['dryness', 'barrier_repair']",
        "rating": 4.8,
        "description": "CeraVe Lightweight Daily Moisturizing Lotion with MVE Technology",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_MST_05",
        "name": "72 HR Hydrating Gel with Hyaluronic Acid & Ceramide",
        "brand": "Dot & Key",
        "category": "Moisturizer",
        "price": 395.0,
        "ingredients": "['Hyaluronic Acid', 'Ceramide NP', 'Japanese Rice Water', 'Probiotics', 'Glycerin']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['oily', 'combination', 'normal']",
        "concerns": "['dryness', 'dullness', 'oiliness']",
        "rating": 4.5,
        "description": "Dot & Key Probiotic 72-Hour Oil-Free Gel Moisturizer with Japanese Rice Water",
        "evidence_tags": "['clinically_tested']"
    },

    # Sunscreens
    {
        "product_id": "IND_SPF_01",
        "name": "Light Fluid SPF 50 Broad Spectrum PA++++ Sunscreen",
        "brand": "Minimalist",
        "category": "Sunscreen",
        "price": 399.0,
        "ingredients": "['Uvinul A Plus', 'Avobenzone', 'Octocrylene', 'Tinosorb M', 'Glycerin', 'Niacinamide', 'Allantoin']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['oily', 'combination', 'normal', 'dry', 'sensitive']",
        "concerns": "['sun_protection', 'acne', 'hyperpigmentation', 'redness']",
        "rating": 4.7,
        "description": "Minimalist Light Fluid SPF 50 with 4 Very High Performance UV Filters without White Cast",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_SPF_02",
        "name": "1% Hyaluronic Sunscreen Aqua Gel SPF 50 PA++++",
        "brand": "The Derma Co",
        "category": "Sunscreen",
        "price": 449.0,
        "ingredients": "['Zinc Oxide', 'Titanium Dioxide', 'Hyaluronic Acid 1%', 'Vitamin E', 'Glycerin', 'Propanediol']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['oily', 'combination', 'normal', 'sensitive']",
        "concerns": "['acne', 'sun_protection', 'hyperpigmentation']",
        "rating": 4.6,
        "description": "The Derma Co 1% Hyaluronic Water-Light Sunscreen Gel with Blue Light & UV Protection",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_SPF_03",
        "name": "Ultra Sheer Dry-Touch Sunblock SPF 50+",
        "brand": "Neutrogena",
        "category": "Sunscreen",
        "price": 320.0,
        "ingredients": "['Helioplex', 'Avobenzone 3%', 'Homosalate 10%', 'Octisalate 5%', 'Octocrylene 2.8%', 'Silica', 'Tocopherol']",
        "fragrance_free": False,
        "alcohol_free": True,
        "skin_types": "['oily', 'combination', 'normal']",
        "concerns": "['sun_protection', 'oiliness']",
        "rating": 4.5,
        "description": "Neutrogena Ultra Sheer Matte Finish Sunscreen with Helioplex Broad Spectrum",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_SPF_04",
        "name": "Watermelon Cooling Glow Sunscreen SPF 50 PA+++",
        "brand": "Dot & Key",
        "category": "Sunscreen",
        "price": 425.0,
        "ingredients": "['Watermelon Extract', 'Hyaluronic Acid', 'Uvinul A Plus', 'Tinosorb S', 'Glycerin']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['combination', 'normal', 'dry']",
        "concerns": "['dullness', 'dryness', 'sun_protection']",
        "rating": 4.6,
        "description": "Dot & Key Watermelon Cooling Zero White Cast Dewy Sunscreen",
        "evidence_tags": "['clinically_tested']"
    },
    {
        "product_id": "IND_SPF_05",
        "name": "CeraVe AM Facial Moisturizing Lotion with SPF 30",
        "brand": "CeraVe",
        "category": "Sunscreen",
        "price": 540.0,
        "ingredients": "['Zinc Oxide', 'Octinoxate', 'Ceramide NP', 'Ceramide AP', 'Ceramide EOP', 'Niacinamide', 'Hyaluronic Acid']",
        "fragrance_free": True,
        "alcohol_free": True,
        "skin_types": "['dry', 'normal', 'sensitive']",
        "concerns": "['barrier_repair', 'dryness', 'sun_protection']",
        "rating": 4.8,
        "description": "CeraVe AM Daily Moisturizing UV Shield with 3 Essential Ceramides & Niacinamide",
        "evidence_tags": "['clinically_tested']"
    }
]

df_new = pd.DataFrame(new_products)
combined_df = pd.concat([df_new, existing_df], ignore_index=True)
combined_df.to_csv(products_path, index=False)
print(f"Catalog updated! Total products now: {len(combined_df)}")
